<?xml version="1.0" encoding="utf-8"?><Database Name="QLNongTraiTayBac" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-77FL8U47\SQLEXPRESS;Initial Catalog=QLNongTraiTayBac;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLNongTraiTayBacConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietDDH" Member="ChiTietDDHs">
    <Type Name="ChiTietDDH">
      <Column Name="idDDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idSP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonDatHang_ChiTietDDH" Member="DonDatHang" ThisKey="idDDH" OtherKey="idDDH" Type="DonDatHang" IsForeignKey="true" />
      <Association Name="NongSan_ChiTietDDH" Member="NongSan" ThisKey="idSP" OtherKey="idSP" Type="NongSan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tinh" Member="Tinhs">
    <Type Name="Tinh">
      <Column Name="MaTinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tinh_GiaoHang" Member="GiaoHangs" ThisKey="MaTinh" OtherKey="MaTinh" Type="GiaoHang" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="MaDanhMuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DanhMuc_Loai" Member="Loais" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="Loai" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatHang" Member="DonDatHangs">
    <Type Name="DonDatHang">
      <Column Name="idDDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDatHang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HinhThucGiaoHang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DonDatHang_ChiTietDDH" Member="ChiTietDDHs" ThisKey="idDDH" OtherKey="idDDH" Type="ChiTietDDH" />
      <Association Name="KhachHang_DonDatHang" Member="KhachHang" ThisKey="idKhachHang" OtherKey="idKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoHang" Member="GiaoHangs">
    <Type Name="GiaoHang">
      <Column Name="MaSP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTinh" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tinh_GiaoHang" Member="Tinh" ThisKey="MaTinh" OtherKey="MaTinh" Type="Tinh" IsForeignKey="true" />
      <Association Name="NongSan_GiaoHang" Member="NongSan" ThisKey="MaSP" OtherKey="idSP" Type="NongSan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="idKH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="KhachHang_DonDatHang" Member="DonDatHangs" ThisKey="idKH" OtherKey="idKhachHang" Type="DonDatHang" />
    </Type>
  </Table>
  <Table Name="dbo.Loai" Member="Loais">
    <Type Name="Loai">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaDanhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Loai_NongSan" Member="NongSans" ThisKey="MaLoai" OtherKey="MaLoaiSP" Type="NongSan" />
      <Association Name="DanhMuc_Loai" Member="DanhMuc" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="DanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NongSan" Member="NongSans">
    <Type Name="NongSan">
      <Column Name="idSP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="HinhDaiDien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DSHinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MienPhiGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NhaSanXuat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaLoaiSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NongSan_ChiTietDDH" Member="ChiTietDDHs" ThisKey="idSP" OtherKey="idSP" Type="ChiTietDDH" />
      <Association Name="NongSan_GiaoHang" Member="GiaoHangs" ThisKey="idSP" OtherKey="MaSP" Type="GiaoHang" />
      <Association Name="Loai_NongSan" Member="Loai" ThisKey="MaLoaiSP" OtherKey="MaLoai" Type="Loai" IsForeignKey="true" />
    </Type>
  </Table>
</Database>