//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Context
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string avartar { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string shortDes { get; set; }
        public string fullDescription { get; set; }
        public Nullable<double> price { get; set; }

        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
